const StudentsClassActionsType = {
  SET_CURRENT_CLASS_START: 'SET_CURRENT_CLASS_START',
  SET_CURRENT_CLASS_SUCCESS: 'SET_CURRENT_CLASS_SUCCESS',
  SET_CURRENT_CLASS_FAILURE: 'SET_CURRENT_CLASS_FAILURE',

  FETCH_CLASSES_START: 'FETCH_CLASSES_START',
  FETCH_CLASSES_FAILURE: 'FETCH_CLASSES_FAILURE',
  FETCH_CLASSES_SUCCESS: 'FETCH_CLASSES_SUCCESS',

  FETCH_CLASS_STUDENTS_START: 'FETCH_CLASS_STUDENTS_START',
};

export default StudentsClassActionsType;
