const AttendanceTypes = {
  SET_ATTENDANCE_DATE: 'SET_ATTENDANCE_DATE',
  START_ATTENDANCE: 'START_ATTENDANCE',
  SET_APPOINTMENT: 'SET_APPOINTMENT',
  SET_ATTENDANCE_TEACHER: 'SET_ATTENDANCE_TEACHER',
  SET_ATTENDANCE_LESSON: 'SET_ATTENDANCE_LESSON',
  SAVE_ATTENDANCE_SUCCESS: 'SAVE_ATTENDANCE_SUCCESS',
  FETCH_LESSONS_LIST_START: 'FETCH_LESSONS_LIST_START',
  FETCH_LESSONS_LIST_SUCCESS: 'FETCH_LESSONS_LIST_SUCCESS',
  FETCH_LESSONS_LIST_FAILURE: 'FETCH_LESSONS_LIST_FAILURE',
};

export default AttendanceTypes;
