const UserTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
  CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
  CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE',
};

export default UserTypes;
